version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: f1db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - f1net

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - f1net

  driver-service:
    build: ./driver-service
    container_name: driver-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - eureka-server
    networks:
      - f1net

  team-service:
    build: ./team-service
    container_name: team-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - eureka-server
      - driver-service
    networks:
      - f1net
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8088:8088"
    depends_on:
      - eureka-server
    networks:
      - f1net
  race-service:
    build: ./race-service
    container_name: race-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - eureka-server
    networks:
      - f1net

networks:
  f1net:
    driver: bridge
