server:
  port: 8082

spring:
  application:
    name: team-service

  datasource:
    url: jdbc:postgresql://postgres:5432/f1db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
